spring:
  profiles:
    active: mybatis  # 기본 프로파일은 JPA 사용

  # 공통 데이터소스 설정
  datasource:
    url: jdbc:mariadb://localhost:3307/goorm_db
    username: goorm-board
    password: goorm1234

  # 공통 Thymeleaf 설정
  thymeleaf:
    cache: false

  # 공통 Flyway 설정
  flyway:
    locations: classpath:db/migration/maria
    baseline-on-migrate: true
    validate-on-migrate: false
    clean-on-validation-error: true
    repair-on-migrate: true


  # 파일 업로드 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

# 공통 로깅 설정
logging:
  level:
    org.springframework.security: DEBUG
    io.goorm.board.service.UserService: DEBUG
    io.goorm.board.controller.AuthController: DEBUG
    org.springframework.security.authentication: TRACE
    org.springframework.security.web: TRACE
  charset:
    console: UTF-8
    file: UTF-8

# JWT 설정
jwt:
  secret: ${JWT_SECRET:myVeryLongSecretKeyThatIsAtLeast256BitsLong123456789}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:900000}    # 15분 (밀리초)
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7일 (밀리초)

# 애플리케이션 설정
app:
  upload:
    # 웹에서 접근 가능한 파일들 (이미지 등)
    web-root: /src/main/resources/static/uploads
    # 웹에서 접근 불가능한 문서들 (엑셀 등)
    document-root: /app/documents